---

- hosts: all

  tasks:
  - name: create dir for maven
    shell: mkdir /opt/maven ; 
    ignore_errors: yes

    #  - name: download maven pkg
    #shell: cd /opt/maven; wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz ; tar -xvzf apache-maven-3.6.3-bin.tar.gz


    
    #    lineinfile:
    #     path: /root/.bash_profile
    #     insertafter: "^JAVA_HOME"
    #     line: "M2_HOME=/opt/maven/apache-maven-3.6.1"
    #     line: "M2=/opt/maven/apache-maven-3.6.3/bin"
    #     firstmatch: yes
    #     state: present
    #register: lineinfileexample
    #

  - name: Download foo.conf
    get_url:
      url: https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /opt/maven/

  - name: extract download file
    shell: cd /opt/maven;tar -xvzf apache-maven-3.6.3-bin.tar.gz


  - name: set maven path in server 
    template:
      src: /tmp/.bash_profile
      dest: /root/.bash_profile
